### ISSUE TITLE
Add 'Domain ID' field on the profile drop-down menu

### ISSUE THREAD

**Issue by jbokyung2** [cloudforet-io/cloudforet#73]

**Comment by jbokyung2** [comment]
![Image](https://user-images.githubusercontent.com/91929073/206364374-f034d7cb-631a-4e7b-b33a-b787c880ec60.png)

**Comment by dsict** [comment]
Design Link: https://www.figma.com/file/e1ACMcvRIUHnlwLVMLjn2T/Console-Components?node-id=199%3A79047&t=rkZX39DCz7Z2xZl7-1
